[etcd]
vm-1 ansible_host=93.77.187.15
vm-2 ansible_host=93.77.187.89
vm-3 ansible_host=84.252.131.77

[postgresql]
vm-1
vm-2
vm-3

[patroni]
vm-1
vm-2
vm-3

[cluster:children]
etcd
postgresql
patroni

[all:vars]
ansible_user=yc-user
ansible_python_interpreter=/usr/bin/python3
